server:
  port: 8080
spring:
  jpa:
    hibernate:
      # 이것도 dev와 prod를 나눠가져가도 된다
      ddl-auto: validate # 개발 환경에서는 create-drop, 운영 환경에서는 validate 권장
      #최초 세팅에만 updata를 쓰고 그 이후는 none만 써

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}